### ISSUE TITLE
How to fixed zoom issue for mobile device ?

### ISSUE THREAD

**Issue by nahidthenh** [nahidthenh/jadoo-travel-agency-landing-page#1]

**Comment by khondokararif** [comment]
Try this
 <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover, user-scalable=no">

**Comment by khondokararif** [comment]
<meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover, user-scalable=no">

**Comment by khondokararif** [comment]
""" <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover, user-scalable=no"> """

**Comment by khondokararif** [comment]
content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover, user-scalable=no"

**Comment by nahidthenh** [comment]
Thanks.
